workflow:
  - .github/*.yml
  - .github/workflows/**/*

dependencies:
  - yarn.lock
  - package.json

source:
  - src/**/*.tsx
  - src/**/*.ts
  - src/**/*.jsx
  - src/**/*.js

styling:
  - src/**/*.css
  - src/**/*.scss
  - src/**/*.sass

assets:
  - assets/*

config:
  - .eslintignore
  - .eslintrc.json
  - .prettierrc
  - .stylelint.json
  - tsconfig.json
  - .gitignore
